f1=open("C:\\Users\\user\\OneDrive\\Documents\\Desktop\\Pythonworks\\datasets\\input.txt","w")
string=input("enter a string:")
f1.write(string)
f1=open("C:\\Users\\user\\OneDrive\\Documents\\Desktop\\Pythonworks\\datasets\\input.txt","r")
content=f1.read()
f1.close()
print(content)